### ISSUE TITLE
Account creation

### ISSUE THREAD

**Issue by roberto-paes** [vseryakov/backendjs#2]
I'm trying to create a new user in a clean installation following the documentation:
"/account/add?name=test&login=test@test.com&secret=test123&gender=f&phone=1234567"

But I got this error message:
"Not Found
Cannot GET /account/add?name=test&login=test@test.com&secret=test123&gender=f&phone=1234567"

Congrats for the great job!

**Comment by vseryakov** [comment]
Sorry for delay, i need to update the docs, accounts module is not enabled by default

**Comment by vseryakov** [comment]
docs updated
